level_0 = {
		'terrain': '../levels/0/level_0_terrain.csv',
		'coins':'../levels/0/level_0_coins.csv',
		'fg palms':'../levels/0/level_0_fg_palms.csv',
		'bg palms':'../levels/0/level_0_bg_palms.csv',
		'crates': '../levels/0/level_0_crates.csv',
		'enemies':'../levels/0/level_0_enemies.csv',
		'constraints':'../levels/0/level_0_constraints.csv',
		'player': '../levels/0/level_0_player.csv',
		'grass': '../levels/0/level_0_grass.csv',
		'node_pos': (350,400),
		'unlock': 1,
		'node_graphics': '../graphics/overworld/0',
        'node_text': "Earth"}
level_1 = {
		'terrain': '../levels/1/level_1_terrain.csv',
		'coins':'../levels/1/level_1_coins.csv',
		'fg palms':'../levels/1/level_1_fg_palms.csv',
		'bg palms':'../levels/1/level_1_bg_palms.csv',
		'crates': '../levels/1/level_1_crates.csv',
		'enemies':'../levels/1/level_1_enemies.csv',
		'constraints':'../levels/1/level_1_constraints.csv',
		'player': '../levels/1/level_1_player.csv',
		'grass': '../levels/1/level_1_grass.csv',
		'node_pos': (250,400),
		'node_graphics': '../graphics/overworld/1',
		'unlock': 2,
        'node_text': "Venus"
		}
level_4= {
		'terrain': '../levels/2/level_2_terrain.csv',
		'coins':'../levels/2/level_2_coins.csv',
		'fg palms':'../levels/2/level_2_fg_palms.csv',
		'bg palms':'../levels/2/level_2_bg_palms.csv',
		'crates': '../levels/2/level_2_crates.csv',
		'enemies':'../levels/2/level_2_enemies.csv',
		'constraints':'../levels/2/level_2_constraints.csv',
		'player': '../levels/2/level_2_player.csv',
		'grass': '../levels/2/level_2_grass.csv',
		'node_pos': (600,400),
		'node_graphics': '../graphics/overworld/4',
		'unlock': 3,
        'node_text': "Jupiter"}
level_2 = {
		'terrain': '../levels/2/level_2_terrain.csv',
		'coins':'../levels/2/level_2_coins.csv',
		'fg palms':'../levels/2/level_2_fg_palms.csv',
		'bg palms':'../levels/2/level_2_bg_palms.csv',
		'crates': '../levels/2/level_2_crates.csv',
		'enemies':'../levels/2/level_2_enemies.csv',
		'constraints':'../levels/2/level_2_constraints.csv',
		'player': '../levels/2/level_2_player.csv',
		'grass': '../levels/2/level_2_grass.csv',
		'node_pos': (450,400),
		'node_graphics': '../graphics/overworld/3',
		'unlock': 4,
        'node_text': "Mars"}
level_5 = {
		'terrain': '../levels/2/level_2_terrain.csv',
		'coins':'../levels/2/level_2_coins.csv',
		'fg palms':'../levels/2/level_2_fg_palms.csv',
		'bg palms':'../levels/2/level_2_bg_palms.csv',
		'crates': '../levels/2/level_2_crates.csv',
		'enemies':'../levels/2/level_2_enemies.csv',
		'constraints':'../levels/2/level_2_constraints.csv',
		'player': '../levels/2/level_2_player.csv',
		'grass': '../levels/2/level_2_grass.csv',
		'node_pos': (800,400),
		'node_graphics': '../graphics/overworld/5',
		'unlock': 5,
        'node_text': "Saturn"}
level_3= {
		'terrain': '../levels/2/level_2_terrain.csv',
		'coins':'../levels/2/level_2_coins.csv',
		'fg palms':'../levels/2/level_2_fg_palms.csv',
		'bg palms':'../levels/2/level_2_bg_palms.csv',
		'crates': '../levels/2/level_2_crates.csv',
		'enemies':'../levels/2/level_2_enemies.csv',
		'constraints':'../levels/2/level_2_constraints.csv',
		'player': '../levels/2/level_2_player.csv',
		'grass': '../levels/2/level_2_grass.csv',
		'node_pos': (150,400),
		'node_graphics':'../graphics/overworld/2',
		'unlock': 5,
        'node_text': "Mercury"}
level_6 = {
		'terrain': '../levels/2/level_2_terrain.csv',
		'coins':'../levels/2/level_2_coins.csv',
		'fg palms':'../levels/2/level_2_fg_palms.csv',
		'bg palms':'../levels/2/level_2_bg_palms.csv',
		'crates': '../levels/2/level_2_crates.csv',
		'enemies':'../levels/2/level_2_enemies.csv',
		'constraints':'../levels/2/level_2_constraints.csv',
		'player': '../levels/2/level_2_player.csv',
		'grass': '../levels/2/level_2_grass.csv',
		'node_pos': (1000,400),
		'node_graphics':'../graphics/overworld/6',
		'unlock': 6,
        'node_text': "Neptune"}
level_7 = {
		'terrain': '../levels/2/level_2_terrain.csv',
		'coins':'../levels/2/level_2_coins.csv',
		'fg palms':'../levels/2/level_2_fg_palms.csv',
		'bg palms':'../levels/2/level_2_bg_palms.csv',
		'crates': '../levels/2/level_2_crates.csv',
		'enemies':'../levels/2/level_2_enemies.csv',
		'constraints':'../levels/2/level_2_constraints.csv',
		'player': '../levels/2/level_2_player.csv',
		'grass': '../levels/2/level_2_grass.csv',
		'node_pos': (1150,400),
		'node_graphics':'../graphics/overworld/7',
		'unlock': 7,
        'node_text': "Uranus"}

levels = {
	0: level_0,
	1: level_1,
	2: level_2,
	3: level_3,
	4: level_4,
	5: level_5,
    6: level_6,
    7: level_7}